# Generated by Django 3.1.6 on 2021-02-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('game_time', models.DurationField()),
                ('flips', models.BigIntegerField()),
                ('finish_at', models.TimeField(auto_now=True)),
            ],
        ),
    ]
