# Generated by Django 3.1.6 on 2021-02-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game_time',
            field=models.DurationField(),
        ),
    ]
